<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServicesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('services')->delete();

        \DB::table('services')->insert([
            0 => [
                'id' => 1,
                'service_name' => 'Architecture Discovery',
                'description' => '* The architect works closely with stakeholders to understand and document the business problem or opportunity the project might address 
* The architect works with the business analyst to identify and document success metrics and any potential design constraints. 
* the architect describes the general shape of the solution scope.',
                'required_skills' => '["architecture"]',
                'hours_cost' => '1.00',
                'created_at' => '2024-11-15 05:25:52',
                'updated_at' => '2024-11-15 05:41:09',
            ],
            1 => [
                'id' => 2,
                'service_name' => 'Conceptual Design',
                'description' => '* Based on well described business needs, the architect will review existing systems for re-use.
* The architect will outline the key solution components, possible technologies and how they will integrate with existing systems
* The architect will NOT provide a design that can be implemented, nor will they gain endorsement from EA or Cyber with this service',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:43:57',
                'updated_at' => '2024-11-15 05:43:57',
            ],
            2 => [
                'id' => 3,
                'service_name' => 'Governance Approval',
                'description' => '* The architect will take a design, either a conceptual one or one generated by others and ensure it complies to standards.
* the architect will guide the design through the necessary cyber and EA approvals, working with stakeholders if necessary
* This service will NOT develop a design, nor will it manage large changes to an existing design',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:45:40',
                'updated_at' => '2024-11-15 05:45:40',
            ],
            3 => [
                'id' => 4,
                'service_name' => 'Solution Architecture Design',
                'description' => '* The architect will develop a comprehensive Solution Architecture Document (SAD)
* The architecture will ensure the design in the SAD is endorsed by Cyber and EA as necessary 
* The SAD will go through peer and leader review for quality assurance',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:47:38',
                'updated_at' => '2024-11-15 05:47:38',
            ],
            4 => [
                'id' => 5,
                'service_name' => 'Options analysis',
                'description' => '* The architect will consider a number of options that could resolve the business needs and provide a report showing pros and cons for each options as well as a recommendation',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:48:51',
                'updated_at' => '2024-11-15 05:48:51',
            ],
            5 => [
                'id' => 6,
                'service_name' => 'Market Survey',
                'description' => '* The architect will investigate options available on the market at present, conduct an RFI if necessary and generate a report explaining the relative benefits and costs for each market option.',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:50:22',
                'updated_at' => '2024-11-15 05:50:22',
            ],
            6 => [
                'id' => 7,
                'service_name' => 'Proof of Concept management',
                'description' => '* The architect will assist the vendor in setting up a Proof of Concept (POC) study, ensuring all Cyber requirements are met.
* The architect will report on the outcome of the POC, including any deviations from the original proposal',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:52:08',
                'updated_at' => '2024-11-15 05:52:08',
            ],
            7 => [
                'id' => 8,
                'service_name' => 'Gap Analysis',
                'description' => '* The architect will review the current state or proposed design and document all non-compliance items between standards, architectureal direction and cyber requirements.',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:53:25',
                'updated_at' => '2024-11-15 05:53:25',
            ],
            8 => [
                'id' => 9,
                'service_name' => 'Prefeasibility Study',
                'description' => '* The architect will provide a pre-feasibility study component',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:54:08',
                'updated_at' => '2024-11-15 05:54:08',
            ],
            9 => [
                'id' => 10,
                'service_name' => 'Feasibility Study',
                'description' => '* The architect will provide a feasibility study component',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:54:27',
                'updated_at' => '2024-11-15 05:54:27',
            ],
            10 => [
                'id' => 11,
                'service_name' => 'Definitive Engineering Study',
                'description' => '* The architect will provide a definitive engineering study component',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:54:54',
                'updated_at' => '2024-11-15 05:54:54',
            ],
            11 => [
                'id' => 12,
                'service_name' => 'Technical Leader Service',
                'description' => '* The architect will provide a technical leadership service',
                'required_skills' => '[""]',
                'hours_cost' => null,
                'created_at' => '2024-11-15 05:55:28',
                'updated_at' => '2024-11-15 05:55:28',
            ],
        ]);

    }
}
