name: Deploy

# Trigger the workflow on push and 
# pull request events on the production branch

on:
  push:
    branches:
      - staging
  # manual
  workflow_dispatch:
    inputs:
      tags:
        description: 'tag'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH 
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          port: 22
          run: ls -al

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, zip, gd, pdo_mysql, redis, memcached, imagick
    
      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy ${{ secrets.SSH_HOST }} -o branch=main -o keep_releases=3 -vvv
